"""Where to collect keys, and which feed they unlock."""

PORTALS = [
    {
        "id": "dhan",
        "name": "DhanHQ",
        "role": "Primary NSE + MCX + F&O quotes (your stated source)",
        "url": "https://web.dhan.co",
        "docs": "https://dhanhq.co/docs/v2/",
        "how": "This board needs Client ID + Access Token only (24h). API Key and Secret are created only on Dhan Web (toggle API Key on Access DhanHQ APIs) — Dhan has no API that mints those from a token. Use Connect below to verify the token.",
        "url": "https://web.dhan.co",
        "docs": "https://dhanhq.co/docs/v2/authentication/",
        "fields": ["dhan_client_id", "dhan_access_token", "dhan_api_key", "dhan_api_secret"],
        "priority": 1,
    },
    {
        "id": "firstock",
        "name": "Firstock Connect",
        "role": "Alternate India broker quotes (NSE/MCX) if Dhan is down",
        "url": "https://firstock.in/api/",
        "docs": "https://firstock.in/api/docs/key-generation/",
        "how": "Login to the key portal → API Keys → Generate appkey + vendor code. Login API returns jKey/susertoken. Paste jKey here; do not store the account password in this app.",
        "fields": ["firstock_user_id", "firstock_vendor_code", "firstock_api_key", "firstock_jkey"],
        "priority": 2,
    },
    {
        "id": "delta",
        "name": "Delta Exchange India",
        "role": "Crypto derivatives: mark price, funding, OI (BTC/ETH/SOL)",
        "url": "https://www.delta.exchange/app/account/manageapikeys",
        "docs": "https://docs.delta.exchange/",
        "how": "Profile → API Keys → Create. Use India production https://api.india.delta.exchange. Public tickers work without a key; key is only for account/funding if you want it. Read-only is enough.",
        "fields": ["delta_api_key", "delta_api_secret"],
        "priority": 3,
    },
    {
        "id": "shark",
        "name": "Shark Exchange",
        "role": "Optional extra crypto/venue feed — paste REST base URL if their docs differ",
        "url": "https://www.google.com/search?q=shark+exchange+api+key",
        "docs": "",
        "how": "Create a read-only API key on the exchange website. Paste base URL + key. This dashboard will not place orders.",
        "fields": ["shark_base_url", "shark_api_key", "shark_api_secret"],
        "priority": 4,
    },
    {
        "id": "coingecko",
        "name": "CoinGecko",
        "role": "Crypto market cap, dominance, aggregated spot",
        "url": "https://www.coingecko.com/en/api/pricing",
        "docs": "https://docs.coingecko.com/",
        "how": "Sign up → Developers → API key (Demo is enough for V1).",
        "fields": ["coingecko_api_key"],
        "priority": 5,
    },
    {
        "id": "tradingview",
        "name": "TradingView",
        "role": "Clean charts on the dashboard (widgets). Not a broker feed.",
        "url": "https://www.tradingview.com/widget/",
        "docs": "https://www.tradingview.com/widget-docs/widgets/charts/advanced-chart/",
        "how": "No API key required for public widgets. Charts use BINANCE:BTCUSDT, NSE:NIFTY, MCX:GOLD1!. Paid TradingView data is optional later.",
        "fields": [],
        "priority": 6,
    },
    {
        "id": "news",
        "name": "News (context only)",
        "role": "Reuters/BBC/CoinDesk RSS already used. Optional NewsAPI for more.",
        "url": "https://newsapi.org/register",
        "docs": "https://newsapi.org/docs",
        "how": "Primary prices still come from Dhan/Delta. NewsAPI is interpretation only.",
        "fields": ["newsapi_key"],
        "priority": 7,
    },
    {
        "id": "deepseek",
        "name": "DeepSeek (WHY? explainers)",
        "role": "Turns the alert + news into simple English when you tap WHY?",
        "url": "https://platform.deepseek.com/api_keys",
        "docs": "https://api-docs.deepseek.com/",
        "how": "Create an API key. Paste it here. The board only sends the alert, related headlines and calendar — never your broker tokens.",
        "fields": ["deepseek_api_key"],
        "priority": 8,
    },
]

LIVE_FEEDS = [
    {
        "name": "DhanHQ Data APIs",
        "url": "https://dhanhq.co/docs/v2/market-quote/",
        "use": "Primary live NSE / BSE / MCX LTP, depth, and candles (this board).",
        "cost": "Trading APIs free; Data APIs billed on Dhan. Need a valid 24h access token + data plan.",
    },
    {
        "name": "Firstock Connect",
        "url": "https://firstock.in/api/",
        "use": "Alternate India broker quotes if Dhan is down.",
        "cost": "Broker account + API keys.",
    },
    {
        "name": "Upstox Market Data",
        "url": "https://upstox.com/developer/api-documentation/market-data-feed/",
        "use": "NSE/BSE/MCX websocket + REST if you prefer Upstox.",
        "cost": "Upstox account; market-data add-on as per their tariff.",
    },
    {
        "name": "Angel One SmartAPI",
        "url": "https://smartapi.angelone.in/",
        "use": "Live quotes and WebSocket for NSE/MCX.",
        "cost": "Angel One account.",
    },
    {
        "name": "Zerodha Kite Connect",
        "url": "https://kite.trade/",
        "use": "Official retail live quotes for NSE/BSE/MCX.",
        "cost": "Paid Kite Connect subscription (not delayed Yahoo).",
    },
    {
        "name": "Fyers API",
        "url": "https://myapi.fyers.in/docs/",
        "use": "India cash/F&O/commodity live data.",
        "cost": "Fyers account + API.",
    },
    {
        "name": "TrueData / Global Datafeeds",
        "url": "https://www.truedata.in/",
        "use": "Vendor tick feed if you need multi-terminal licensed NSE/MCX.",
        "cost": "Paid exchange-licensed feed.",
    },
    {
        "name": "Binance (spot)",
        "url": "https://binance-docs.github.io/apidocs/spot/en/",
        "use": "Already used for BTC/ETH live crypto — no Yahoo.",
        "cost": "Free public ticker.",
    },
    {
        "name": "Polygon.io",
        "url": "https://polygon.io/",
        "use": "US stocks/indices live (SPX, NDX) instead of delayed Yahoo global.",
        "cost": "Paid stocks plan.",
    },
    {
        "name": "TradingView Advanced Charts",
        "url": "https://www.tradingview.com/widget-docs/widgets/charts/advanced-chart/",
        "use": "Paid TV data for display-only charts; not a broker LTP feed.",
        "cost": "TradingView subscription.",
    },
]

WEBSITES = [
    {"name": "NSE India", "url": "https://www.nseindia.com", "use": "Indices, stocks, VIX, reports"},
    {"name": "BSE India", "url": "https://www.bseindia.com", "use": "SENSEX, BANKEX"},
    {"name": "MCX India", "url": "https://www.mcxindia.com/market-data/market-watch", "use": "Gold, silver, crude, OI"},
    {"name": "DhanHQ", "url": "https://web.dhan.co", "use": "Broker NSE/MCX live quotes"},
    {"name": "Firstock", "url": "https://firstock.in/api/", "use": "Alternate India broker API"},
    {"name": "Binance", "url": "https://www.binance.com", "use": "BTC candle feed"},
    {"name": "Delta Exchange India", "url": "https://india.delta.exchange", "use": "Crypto derivatives"},
    {"name": "CoinGecko", "url": "https://www.coingecko.com", "use": "Crypto market structure"},
    {"name": "Yahoo Finance", "url": "https://finance.yahoo.com", "use": "Delayed research only (US indices / FX) — not NSE/MCX live"},
    {"name": "BLS", "url": "https://www.bls.gov", "use": "US CPI / jobs calendar"},
    {"name": "Federal Reserve", "url": "https://www.federalreserve.gov", "use": "FOMC / rates"},
    {"name": "EIA", "url": "https://www.eia.gov", "use": "Crude inventories"},
    {"name": "RBI", "url": "https://www.rbi.org.in", "use": "India policy"},
    {"name": "BBC / CoinDesk", "url": "https://www.bbc.com/news/business", "use": "News context only"},
]

FIELD_LABELS = {
    "dhan_client_id": "Dhan client ID",
    "dhan_access_token": "Dhan access token",
    "dhan_api_key": "Dhan API key",
    "dhan_api_secret": "Dhan API secret",
    "firstock_user_id": "Firstock user ID",
    "firstock_vendor_code": "Firstock vendor code",
    "firstock_api_key": "Firstock app key",
    "firstock_jkey": "Firstock jKey / session token",
    "delta_api_key": "Delta API key",
    "delta_api_secret": "Delta API secret",
    "shark_base_url": "Shark REST base URL",
    "shark_api_key": "Shark API key",
    "shark_api_secret": "Shark API secret",
    "coingecko_api_key": "CoinGecko API key",
    "newsapi_key": "NewsAPI key",
    "deepseek_api_key": "DeepSeek API key",
}

SECRET_FIELDS = {k for k in FIELD_LABELS if "secret" in k or "token" in k or k.endswith("_jkey") or k.endswith("_key")}
